# Generated by Django 4.2.20 on 2025-03-12 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('numero', models.IntegerField(unique=True)),
                ('agencia', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='cliente.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ContaCorrente',
            fields=[
                ('conta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='conta.conta')),
                ('limite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('limite_saques', models.IntegerField(default=3)),
            ],
            bases=('conta.conta',),
        ),
    ]
