services:
  web:
    container_name: django_app
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=bancoApi.settings

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery_worker
    depends_on:
      - redis
      - web
    command: celery -A bancoapi worker --loglevel=info
    environment:
      - DJANGO_SETTINGS_MODULE=bancoapi.settings
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery-beat:
    build: .
    container_name: celery_beat
    depends_on:
      - redis
      - web
    command: celery -A bancoapi beat --loglevel=info
    environment:
      - DJANGO_SETTINGS_MODULE=bancoapi.settings
      - CELERY_BROKER_URL=redis://redis:6379/0

volumes:
  postgres_data:
