# Generated by Django 4.2.20 on 2025-03-12 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transacao', '0001_initial'),
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='conta.conta')),
            ],
        ),
        migrations.CreateModel(
            name='TransacaoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historico.historico')),
                ('transacao_deposito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transacao.deposito')),
                ('transacao_saque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transacao.saque')),
            ],
        ),
        migrations.AddField(
            model_name='historico',
            name='transacoes_deposito',
            field=models.ManyToManyField(blank=True, through='historico.TransacaoHistorico', to='transacao.deposito'),
        ),
        migrations.AddField(
            model_name='historico',
            name='transacoes_saque',
            field=models.ManyToManyField(blank=True, through='historico.TransacaoHistorico', to='transacao.saque'),
        ),
    ]
